name: "flake check"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu", "macos" ]
        target: [ "26.05", "unstable" ]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ matrix.target }}-

      - name: build stable
        if: matrix.target != 'unstable'
        run: |
          nix build -L \
            --override-input nixpkgs github:NixOS/nixpkgs/nixos-26.05 \
            --override-input nixvim github:nix-community/nixvim/nixos-26.05

      - name: build unstable
        if: matrix.target == 'unstable'
        run: |
          nix build -L
