name: "flake check"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ "24.11", "unstable" ]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: build stable
        if: matrix.target != 'unstable'
        run: |
          # TODO: switch to nixvim/nixos-24.11 when available
          nix build -L \
            --override-input nixpkgs github:NixOS/nixpkgs/nixos-24.11 \
            --override-input home-manager github:nix-community/home-manager/release-24.11 \
            --override-input nixvim github:nix-community/nixvim

      - name: build unstable
        if: matrix.target == 'unstable'
        run: |
          nix build -L
