name: "flake check"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ "25.05", "unstable" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}

      - name: build stable
        if: matrix.target != 'unstable'
        run: |
          nix build -L \
            --override-input nixpkgs github:NixOS/nixpkgs/nixos-25.05 \
            --override-input nixvim github:nix-community/nixvim/nixos-25.05

      - name: build unstable
        if: matrix.target == 'unstable'
        run: |
          nix build -L
