name: "flake check"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ "unstable", "stable" ]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      # TODO: bring back with 24.11
      # - name: build stable
      #   if: matrix.target == 'stable'
      #   run: |
      #     nix build -L \
      #       --override-input nixpkgs github:NixOS/nixpkgs/nixos-24.05 \
      #       --override-input home-manager github:nix-community/home-manager/release-24.05 \
      #       --override-input nixvim github:nix-community/nixvim/nixos-24.05

      - name: build unstable
        if: matrix.target != 'stable'
        run: |
          nix build -L
